title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Brauchli, Nicolas
email: NicoBraHTW@gmx.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
